keboola_o_auth_homepage:
    path:     /hello/{name}
    defaults: { _controller: KeboolaOAuthBundle:Default:index }

keboola_o_auth_test:
    path: /test
    defaults: { _controller: KeboolaOAuthBundle:V10:test }

keboola_o_auth_oauth1:
    path: /auth10
    defaults: { _controller: KeboolaOAuthBundle:V10:getOAuth }
    methods:  [POST]

keboola_o_auth_oauth_external1:
    path: /auth10
    defaults: { _controller: KeboolaOAuthBundle:V10:externalAuth }
    methods:  [GET]

keboola_o_auth_oauth_callback1:
    path: /auth10-callback
    defaults: { _controller: KeboolaOAuthBundle:V10:getOAuthCallback }

keboola_o_auth_oauth2:
    path: /auth20
    defaults: { _controller: KeboolaOAuthBundle:V20:getOAuth }
    methods:  [POST]

keboola_o_auth_oauth_external2:
    path: /auth20
    defaults: { _controller: KeboolaOAuthBundle:V20:externalAuth }
    methods:  [GET]

keboola_o_auth_oauth_callback2:
    path: /auth20-callback
    defaults: { _controller: KeboolaOAuthBundle:V20:getOAuthCallback }

keboola_o_auth_get_credentials:
    path: /get/{api}/{id}
    defaults: { _controller: KeboolaOAuthBundle:Credentials:get }
